SET LINESIZE 250
SET PAGESIZE 100
CLEAR COLUMNS
CLEAR BREAKS
CLEAR COMPUTES
TTITLE OFF
BTITLE OFF
REPFOOTER OFF

CREATE OR REPLACE VIEW FIND_DATE_TERMINAL AS
SELECT BS.SCHEDULEID ,DEPARTUREDATE, TO_CHAR(DEPARTURETIME, 'HH24:MI') AS DEPARTURETIME, DEPARTURETERMINAL, ARRIVALTERMINAL, TO_CHAR(DURATION, 'HH24:MI') AS DURATION
FROM BUSSCHEDULE BS, ROUTE R
WHERE BS.ROUTENO = R.ROUTENO;

COLUMN MEMBERID			heading 'Member ID'			format a10
column SCHEDULEID		heading 'Schedule ID'			format a13
column DEPARTUREDATE		heading 'Date'				format a12
column DEPARTURETIME		heading 'Time'				format a5
column DEPARTURETERMINAL	heading 'Departure Terminal'		format a25
column ARRIVALTERMINAL		heading 'Arrival Terminal'		format a25
COLUMN DURATION			heading 'Duration'			format a10

ACCEPT V_MEMBERID CHAR FORMAT 'a20'- 
PROMPT 'ENTER MEMBERID TO FIND: '

ttitle 'PENDING SCHEDULE FOR CUSTOMER '&V_MEMBERID'' skip 1-
'------------------------------------' skip 1-
left 'Page:' format 999 sql.pno skip 2
repfooter skip 1 '---End of Report---'

BREAK ON REPORT

SELECT FD.SCHEDULEID, DEPARTUREDATE, DEPARTURETIME , DEPARTURETERMINAL, ARRIVALTERMINAL, DURATION
FROM MEMBER M, TRANSACTION T, TRANSACTIONDETAILS TD, FIND_DATE_TERMINAL FD
WHERE M.MEMBERID = '&V_MEMBERID' AND M.MEMBERID = T.MEMBERID AND T.TRANSACTIONID = TD.TRANSACTIONID AND TD.SCHEDULEID = FD.SCHEDULEID
AND FD.DEPARTUREDATE >= SYSDATE
ORDER BY FD.SCHEDULEID;