DROP SEQUENCE transaction_seq;
DROP SEQUENCE member_seq;

CREATE SEQUENCE transaction_seq
		INCREMENT BY 1
		START WITH 24658
		NOCACHE
		NOCYCLE;

CREATE SEQUENCE member_seq
		INCREMENT BY 1
		START WITH 1501
		NOCACHE
		NOCYCLE;