CREATE OR REPLACE TRIGGER TRG_CHECK_TRANSACTION
BEFORE INSERT ON transaction
FOR EACH ROW
BEGIN
	IF (TO_DATE(SYSDATE, 'DD-MM-YYYY') - TO_DATE(:NEW.PURCHASEDATE, 'DD-MM-YYYY') < 0) THEN
		RAISE_APPLICATION_ERROR(-20102, 'INVALID PURCHASE DATE');
	END IF;

	IF NOT (:new.paymentType IN ('E-Wallet', 'Debit Card/Credit Card', 'Online Banking')) THEN
		RAISE_APPLICATION_ERROR(-20103, 'INVALID PAYMENT TYPE');
	END IF;
END;
/

INSERT INTO TRANSACTION VALUES ('T24660', 'M1060', TO_DATE('30-OCT-2021', 'DD-MON-YYYY'), 500.00, 'E-Wallet');

INSERT INTO TRANSACTION VALUES ('T24660', 'M1060', TO_DATE('27-AUG-2021', 'DD-MON-YYYY'), 500.00, 'Cash');